name: psws_storage
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  cupertino_icons: ^1.0.2

  flutter_swipe_action_cell: ^3.0.1

  # router:
  auto_route: ^7.2.0

  flutter_svg: ^2.0.0+1

  # storage:
  hive: ^2.2.1
  hive_flutter: ^1.1.0

  flutter_quill: ^7.1.19

  # secure_storage:
  flutter_secure_storage: ^8.0.0

  # Back button interceptor:
  back_button_interceptor: ^6.0.0

  # uuid
  uuid_type: ^2.0.0

  get_it: ^7.2.0

  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  #fingerprint
  local_auth: ^2.1.3


  #export files:
  permission_handler: ^10.2.0
  path_provider: ^2.0.11
  collection: ^1.16.0

  file_picker: ^5.3.1

  #crypto and encrypt
  crypto: ^3.0.2
  encrypt: ^5.0.1

  loader_overlay: ^2.1.0
  share_plus: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # router:
  auto_route_generator: ^7.1.1

  hive_generator: ^2.0.0

  build_runner: ^2.1.5

  flutter_lints: ^2.0.1
  json_serializable: ^6.5.4
  json_annotation: ^4.6.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/icons/
