name: psws_storage
description: A new Flutter project.

version: 1.4.1+10

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.2

  flutter_swipe_action_cell: ^3.0.1

  # router:
  auto_route: ^9.2.2

  flutter_svg: ^2.0.0+1

  # storage:
  hive: ^2.2.1
  hive_flutter: ^1.1.0

  flutter_quill: ^10.8.5

  # secure_storage:
  flutter_secure_storage: ^9.2.3

  # Back button interceptor:
  back_button_interceptor: ^8.0.3

  #privacy_screen
  privacy_screen:
    git:
      url: git@github.com:Tsiuryn/privacy_screen.git
      ref: update-android

  # uuid
  uuid_type: ^2.0.0

  get_it: ^8.0.3

  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  #fingerprint
  local_auth: ^2.1.3


  #export files:
  path_provider: ^2.0.11
  collection: ^1.16.0

  file_picker: ^8.1.7

  #crypto and encrypt
  crypto: ^3.0.2
  # upgrade 5.0.1 version after checking import db
  encrypt: 5.0.1

  loader_overlay: ^4.0.4+1
  share_plus: ^10.1.3

  json_annotation: ^4.8.1
  flutter_cupertino_datetime_picker: ^3.0.0
  google_nav_bar: ^5.0.7
  flutter_heatmap_calendar: ^1.0.5

  #
  drift: ^2.26.0
  path: ^1.9.1
  drift_flutter: ^0.2.4
  flutter_expandable_fab: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # router:
  auto_route_generator: ^9.0.0

  hive_generator: ^2.0.0

  drift_dev: ^2.14.1

  build_runner: ^2.1.5

  flutter_lints: ^5.0.0
  json_serializable: ^6.5.4

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/icons/
